# Site settings
title: Blake DeBray
description: Program Manager, Coach, Human
baseurl: ""
url: ""
logo: /assets/images/logo.svg

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .DS_Store

# Collections
collections:
  workshops:
    output: true
  presentations:
    output: true
  resources:
    output: true
  books:
    output: true
  contacts:
    output: true
  services:
    output: true
