- title: "Authenticity"
  description: "Being myself and continuing to discover who I am."

- title: "Trust"
  description: "Trust others, myself, and systems by default. Create trust where it is missing."

- title: "Safety"
  description: "Create a space where others can be themselves and trust they can be open and vulnerable with me."

- title: "Fairness"
  description: "I believe in fairness and equality for all humans based on compassion, social justice, and empathy."

- title: "Harmony"
  description: "Working together without unnecessary competition or a need of holding power over others."

- title: "Beauty in all things"
  description: "Pausing to to admire the beauty in nature, humanity, design, and all systems for which we interact."

- title: "Adaptability"
  description: "Being able to adapt to change and uncertainty.Plan for a direction while leaving space for learning and iterating as we go."

- title: "Learning"
  description: "Lifelong learning is important to grow and experience life to the fullest. I always look forward to meeting the next version of myself."